### ISSUE TITLE
How do you deal with the records without 'BX' tag in the bam files?

### ISSUE THREAD

**Issue by verne91** [walaj/bxtools#16]

**Comment by walaj** [comment]
They will be completely ignored, since this is a tool to specifically handle operations for labeled reads. I have, however, been allowing for these tag-specific operations to be conducted on other tags than "BX", by passing a command line flag with the desired tag.

If the barcode information is encoded elsewhere (e.g. the readname), ``bxtools`` could be adjusted to handle.

**Comment by verne91** [comment]
Thank you very much.
BTW, I also found that some records in the 10x bam file are abnormal.
The absolute values of 'TLEN' are different in one paired reads.
Do you know the reason?

**Comment by walaj** [comment]
Unfortunately I'm not sure the reason.

**Comment by verne91** [comment]
Thank you anyway.
